### ISSUE TITLE
Questão sobre a atualização de stock

### ISSUE THREAD

**Issue by andrejrcarvalho** [moloni/opencart3#2]
Gostaria de perceber se quando uma  encomenda é passada para o moloni o stock do respetivo produto é atualizado.
Pelo que percebi da analise do codigo os produtos apenas são inseridos e nao existe metodo para os alterar ou para fazer uma movimentação do stock o que me deixa um pouco confuso relativamente a essa questão dos stock.

**Comment by moloni-pt** [comment]
Boa tarde, 

Sempre que uma encomenda é enviada para o Moloni e é criado um documento, a própria acção de criação de um documento já irá descontar o stock no Moloni (se o tipo de documento movimentar stock).

**Comment by andrejrcarvalho** [comment]
Obrigado pelo esclarecimento
